name: Build and Deploy MAUI App

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.100"

      - name: Install MAUI Android
        run: dotnet workload install maui-android

      - name: Build APK
        run: dotnet publish ./WeatherApp/WeatherApp.csproj -f:net8.0-android -c Release -o ./output/android -p:AndroidPackageFormat=apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: ./output/android/*.apk